#!/bin/bash
# set -e

CC="gcc"
CFLAGS="-g -fsanitize=address"
LDFLAGS="-g -fsanitize=address"
INPUT="../main.c ../code/axle/src/*.c"
INCLUDE="../code/axle/include"
OUTPUT="./bin/axle"

mkdir -p ./bin 2>&1 >/dev/null
# rm ./bin/*.o 2>&1 >/dev/null

(cd ./bin && $CC -c $INPUT -I"$INCLUDE" $CFLAGS)
$CC -o "$OUTPUT" ./bin/*.o $LDFLAGS
rm ./bin/*.o
